### ISSUE TITLE
Grumman Duck

### ISSUE THREAD

**Issue by Jetjockey10** [krzysk1/j2f_duck#1]
Oh wow.  What a great choice for FS2.  We sure do need real water.
Ray

**Comment by Jetjockey10** [comment]
The cockpit panel needs some serious work.  Landing gear works, up and down.  External sounds are working.  Beautiful exterior.

**Comment by Jetjockey10** [comment]
I noticed this one came from Turbosquid.  Does this mean there is no 3D now, or that the full 3d will have to be coded in AFS2?

**Comment by krzysk1** [comment]
My model is just the same as on Turbosquid - it has no 3D cockpit.
It is to hard to add 3D and I'm not planning to do this. 

Maybe sb else take it?
